My first pull request
Ahsan12356/Hello-world pull request #1
Opened 2022-03-16 19:08 UTC by Ahsan12356

2022-03-16 19:31 UTC, MeqdamAlqudah requested changes
Hello @Ahsan12356   , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Your code is working ✅
-  ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Feel free to ask me any question slack 🚀
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-03-16 19:31 UTC, MeqdamAlqudah commented on style.css
> +}
[Required ] as mentioned in the requirement style.css must include one class with styles for your header but instead, you just select all h1 elements please use classes instead 
because CSS classes enable you to apply unique style properties 
check this [article](https://blog.hubspot.com/website/what-is-css-class)

2022-03-16 19:31 UTC, MeqdamAlqudah commented on index.html
> +<!DOCTYPE html>
[REQUIRED] Please README file should be descriptive? AKA: Microverse [README template](https://github.com/microverseinc/readme-template) should be used. because it is the best way to document your code so people can understand how to use your project

2022-03-16 19:31 UTC, MeqdamAlqudah commented on index.html
> +<!DOCTYPE html>
[Required] - Please  Pull Request should have a descriptive title telling you what changes are inside.
[Required] - Please Pull Request should have a short summary describing introduced changes in more detail.

![image](https://user-images.githubusercontent.com/74744787/158673656-104d82f1-ec71-4130-b431-8621a20e1a5b.png)

2022-03-16 19:31 UTC, MeqdamAlqudah commented on index.html
> +<!DOCTYPE html>
[Optional] Please make your commits descriptive i.e they describe the action that you did and let them be in the present tense.

![image](https://user-images.githubusercontent.com/74744787/158674091-52b43405-11fc-40de-af0a-d35a27e9d582.png)

like Add HTML file  or  Add CSS file so when you come to your project after  a period you can fully understand your changes log

2022-03-16 19:31 UTC, MeqdamAlqudah commented on index.html
> +<!DOCTYPE html>
[Required] Please Fix your linter errors before requesting a review 

![image](https://user-images.githubusercontent.com/74744787/158674658-7714eff8-0451-45f8-bb69-59f443fafd6c.png)

2022-03-17 07:46 UTC, aimemalaika requested changes
Hi @Ahsan12356, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7](https://user-images.githubusercontent.com/28307960/158747852-e9f4c957-d810-4de4-b468-69b1337714ea.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-17 08:31 UTC, merged